backend:
  name: github
  repo: batipercheron/site-batipercheron
  branch: main

media_folder: "images/materiaux"
public_folder: "images/materiaux"

collections:
  - name: "catalogue"
    label: "Catalogue des Matériaux"
    files:
      - label: "Gestion des Lots en Vente"
        name: "materiaux"
        file: "data/materiaux.json"
        fields:
          - label: "Articles en vente"
            name: "articles"
            widget: "list"
            required: false
            fields:
              - {label: "Titre de l'article", name: "titre", widget: "string"}
              - {label: "Catégorie", name: "categorie", widget: "select", options: ["pierre-de-taille", "terres-cuites", "bois-douvrage", "menuiseries-anciennes"]}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Image Principale", name: "image", widget: "image", required: false}
              - label: "Images supplémentaires (jusqu'à 10)"
                name: "images_secondaires"
                widget: "list"
                required: false
                field: {label: "Photo", name: "photo", widget: "image"}
              - {label: "Quantité", name: "quantite", widget: "string", required: false}
              - {label: "Prix", name: "prix", widget: "string", default: "Sur devis"}
